resources:
- ../base
namePrefix: staging-
patches:
  - target:
      kind: Service
      name: mydep1-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31000
replicas:
  - name: mydep1
    count: 3
