resources:
- ../base
namePrefix: dev-
patches:
  - target:
      kind: Service
      name: mydep1-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32000
replicas:
  count: 2
