apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep1
  name: mydep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep1
  template:
    metadata:
      labels:
        app: mydep1
    spec:
      containers:
      - image: docker.io/httpd
        name: httpd
        ports:
        - containerPort: 80
	- containerPort: 443
	- containerPort: 8080
