apiVersion: v1
kind: Service
metadata:
  name: mydep1-service
spec:
  selector:
    app: mydep1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000
    - name: https
      port: 443
      targetPort: 443
      nodePort: 32000
    - name: metrics
      port: 8080
      targetPort: 8080
      nodePort: 31005
