apiVersion: v1
kind: Service
metadata:
  name: mydep1-service
  labels:
    app: mydep1
spec:
  type: NodePort
  selector:
    app: mydep1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
